services:
  db:
    image: mysql:8.0
    container_name: autorent_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Par00l
      MYSQL_DATABASE: autorent
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  web:
    build: .
    container_name: autorent_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: autorent_pma
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
